//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Membran_Contorl {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Menbran_config : global::System.Configuration.ApplicationSettingsBase {
        
        private static Menbran_config defaultInstance = ((Menbran_config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Menbran_config())));
        
        public static Menbran_config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3140")]
        public int table_width {
            get {
                return ((int)(this["table_width"]));
            }
            set {
                this["table_width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1230")]
        public int table_height {
            get {
                return ((int)(this["table_height"]));
            }
            set {
                this["table_height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.31.250")]
        public string db_host {
            get {
                return ((string)(this["db_host"]));
            }
            set {
                this["db_host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hanhai_manufacture")]
        public string db_name {
            get {
                return ((string)(this["db_name"]));
            }
            set {
                this["db_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chk")]
        public string db_user {
            get {
                return ((string)(this["db_user"]));
            }
            set {
                this["db_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345678")]
        public string db_pass {
            get {
                return ((string)(this["db_pass"]));
            }
            set {
                this["db_pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("瀚海")]
        public string Factory {
            get {
                return ((string)(this["Factory"]));
            }
            set {
                this["Factory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hanhai_management")]
        public string db_mang_name {
            get {
                return ((string)(this["db_mang_name"]));
            }
            set {
                this["db_mang_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Check_days {
            get {
                return ((int)(this["Check_days"]));
            }
            set {
                this["Check_days"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string 待接单状态 {
            get {
                return ((string)(this["待接单状态"]));
            }
            set {
                this["待接单状态"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string 加工中状态 {
            get {
                return ((string)(this["加工中状态"]));
            }
            set {
                this["加工中状态"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string 加工完成状态 {
            get {
                return ((string)(this["加工完成状态"]));
            }
            set {
                this["加工完成状态"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string State_done {
            get {
                return ((string)(this["State_done"]));
            }
            set {
                this["State_done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public string State_undone {
            get {
                return ((string)(this["State_undone"]));
            }
            set {
                this["State_undone"] = value;
            }
        }
    }
}
